/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bureau.of.internal.revenue;

import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sankyo
 */
public class REVIEWER extends javax.swing.JFrame {

    /**
     * Creates new form REVIEWER
     */
    public REVIEWER() {
        initComponents();
        Profile();
        listed();
//        groupsupervisor();
        groupsupervisorComboBox();
        setColor(assign);
        SC.setOpaque(true);

    }

    public void groupsupervisorComboBox() {

        String Dtases = ConnectionDB.GetsNameReturn();
        String DtaseN = ConnectionDB.GetDbName();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = (Connection) DriverManager.getConnection("jdbc:mysql://" + Dtases + ":3306/" + DtaseN + "", "root", "");
            String SQL = "SELECT * FROM `accounts` WHERE `user-level` = '5'";
            Statement PST = connection.createStatement();
            ResultSet resultSet = PST.executeQuery(SQL);
            while (resultSet.next()) {
                jComboBox1.addItem(resultSet.getString(2));

            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(RECEIVING.class.getName()).log(Level.SEVERE, null, ex);
        }

//        TableColumn groupsupervisor = jTable1.getColumnModel().getColumn(9);
//        
//        JComboBox comboBox = new JComboBox();
//        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose" }));
//        comboBox.addItem("Snowboarding");
//        comboBox.addItem("Rowing");
//        comboBox.addItem("Chasing toddlers");
//        comboBox.addItem("Speed reading");
//        comboBox.addItem("Teaching high school");
//        comboBox.addItem("None");
//        groupsupervisor.setCellEditor(new DefaultCellEditor(comboBox));
    }

    public void groupSvisorCombo() {

        String Dtases = ConnectionDB.GetsNameReturn();
        String DtaseN = ConnectionDB.GetDbName();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = (Connection) DriverManager.getConnection("jdbc:mysql://" + Dtases + ":3306/" + DtaseN + "", "root", "");
            String SQL = "SELECT * FROM `accounts` WHERE `user-level` = '5'";
            Statement PST = connection.createStatement();
            ResultSet resultSet = PST.executeQuery(SQL);
            while (resultSet.next()) {

                jTable1.getColumnModel().getColumn(10).setCellEditor(new DefaultCellEditor((JTextField) resultSet));

            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(RECEIVING.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void Profile() {
        String UsernameProfile = PROFILE.GetsNameReturn();
        UserLevel1.setText(UsernameProfile);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SideMenu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        UserLevel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UserLevel1 = new javax.swing.JLabel();
        assign = new javax.swing.JPanel();
        jLabelHome = new javax.swing.JLabel();
        SC = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        HeaderPressed = new javax.swing.JPanel();
        PanelLayer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SideMenu.setBackground(new java.awt.Color(23, 33, 53));
        SideMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(23, 33, 53));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserLevel.setBackground(new java.awt.Color(255, 255, 255));
        UserLevel.setForeground(new java.awt.Color(255, 255, 255));
        UserLevel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLevel.setText("TASK");
        UserLevel.setPreferredSize(new java.awt.Dimension(35, 16));
        jPanel2.add(UserLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 170, 50));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("________________________");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 170, 31));

        UserLevel1.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        UserLevel1.setForeground(new java.awt.Color(255, 255, 255));
        UserLevel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLevel1.setText("NAME");
        UserLevel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        UserLevel1.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(UserLevel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 86, 170, 20));

        SideMenu.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 160));

        assign.setBackground(new java.awt.Color(23, 33, 53));
        assign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                assignMousePressed(evt);
            }
        });

        jLabelHome.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHome.setText("Assign");
        jLabelHome.setPreferredSize(new java.awt.Dimension(35, 16));

        SC.setBackground(new java.awt.Color(255, 255, 255));
        SC.setPreferredSize(new java.awt.Dimension(7, 0));

        javax.swing.GroupLayout SCLayout = new javax.swing.GroupLayout(SC);
        SC.setLayout(SCLayout);
        SCLayout.setHorizontalGroup(
            SCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        SCLayout.setVerticalGroup(
            SCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout assignLayout = new javax.swing.GroupLayout(assign);
        assign.setLayout(assignLayout);
        assignLayout.setHorizontalGroup(
            assignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, assignLayout.createSequentialGroup()
                .addComponent(SC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        assignLayout.setVerticalGroup(
            assignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelHome, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(SC, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        SideMenu.add(assign, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 170, 50));

        getContentPane().add(SideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 520));

        Header.setBackground(new java.awt.Color(62, 101, 181));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 700, 50));

        HeaderPressed.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderPressedMouseDragged(evt);
            }
        });
        HeaderPressed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderPressedMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderPressedLayout = new javax.swing.GroupLayout(HeaderPressed);
        HeaderPressed.setLayout(HeaderPressedLayout);
        HeaderPressedLayout.setHorizontalGroup(
            HeaderPressedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        HeaderPressedLayout.setVerticalGroup(
            HeaderPressedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(HeaderPressed, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 50));

        PanelLayer.setBackground(new java.awt.Color(41, 57, 80));
        PanelLayer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "uniqueid", "taxpayer", "taxpayer", "loano", "examiner", "dateofloa", "dateofloareceipt", "datereceived", "groupsupervisor	"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        PanelLayer.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 680, 310));

        jLabel1.setText("ID");

        jLabel2.setText("GroupSuperVisor");

        jTextField1.setText("#NO");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose" }));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(366, 366, 366))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        PanelLayer.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 350, 130));

        getContentPane().add(PanelLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 700, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HeaderPressedMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderPressedMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_HeaderPressedMouseDragged

    private void HeaderPressedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderPressedMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_HeaderPressedMousePressed

    private void assignMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignMousePressed
        // TODO add your handling code here:
        setColor(assign);
        SC.setOpaque(true);
    }//GEN-LAST:event_assignMousePressed

    String IDTrack;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //UPDATE `docket` SET `groupsupervisor` = 'dada' WHERE `docket`.`id` = 2;
        String ComboValues = jComboBox1.getSelectedItem().toString();
        String ValField = jTextField1.getText();
        String UsernameProfile = PROFILE.GetsNameReturn();

        String Dtases = ConnectionDB.GetsNameReturn();
        String DtaseN = ConnectionDB.GetDbName();

        if (!"Choose".equals(ComboValues) && !"#NO".equals(ValField)) {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection connection = (Connection) DriverManager.getConnection("jdbc:mysql://" + Dtases + ":3306/" + DtaseN + "", "root", "");
                String SQL = "SELECT * FROM `docket` WHERE `uniqueid` = '" + ValField + "' AND `REVIWER` = '" + UsernameProfile + "' ";
//                SELECT * FROM `docket` WHERE `uniqueid` = '0231' AND `REVIWER` = 'rev'
                Statement PST = connection.createStatement();
                ResultSet resultSet = PST.executeQuery(SQL);
                if (resultSet.next()) {
                    String UpSQL = "UPDATE `docket` SET `groupsupervisor` = '" + ComboValues + "' WHERE `docket`.`uniqueid` = '" + ValField + "' AND `groupsupervisor` = ''";
//                    ResultSet resultSetID = PST.executeQuery("UPDATE `docket` SET `groupsupervisor` = 's' WHERE `docket`.`uniqueid` = '" + ValField + "'");
                    if (PST.executeUpdate(UpSQL) != 0) {
                        JOptionPane.showMessageDialog(null, "Success ! ");
                    } else {
                        JOptionPane.showMessageDialog(null, "You Can't Change Group SuperVisor ! ");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Wrong ID#@2010220");
                }

            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(REVIEWER.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (ComboValues.equals("Choose") && ValField.equals("#NO")) {
            JOptionPane.showMessageDialog(null, "Please Input ID#@202001 && Choose GroupSuperVisor");
        } else if (ValField.equals("#NO")) {
            JOptionPane.showMessageDialog(null, "Please Input ID#@202001");
        } else if (ComboValues.equals("Choose")) {
            JOptionPane.showMessageDialog(null, "Please Choose GroupSuperVisor");
        } else {
            JOptionPane.showMessageDialog(null, "Please Contact Admin");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    int xx, yy;

    private void setColor(JPanel pane) {
        pane.setBackground(new Color(41, 57, 80));
    }

    private void resetColor(JPanel[] pane, JPanel[] indicators) {
        for (JPanel pane1 : pane) {
            pane1.setBackground(new Color(23, 35, 51));
        }
        for (JPanel indicator : indicators) {
            indicator.setOpaque(false);
        }
    }

    public void listed() {
        String UsernameProfile = PROFILE.GetsNameReturn();
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("ID");
        table.addColumn("uniqueid");
        table.addColumn("taxpayer");
        table.addColumn("taxableyear");
        table.addColumn("loano");
        table.addColumn("examiner");
        table.addColumn("dateofloa");
        table.addColumn("dateofloareceipt");
        table.addColumn("datereceived");
        table.addColumn("groupsupervisor");

        String Dtases = ConnectionDB.GetsNameReturn();
        String DtaseN = ConnectionDB.GetDbName();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = (Connection) DriverManager.getConnection("jdbc:mysql://" + Dtases + ":3306/" + DtaseN + "", "root", "");
            String SQL = "SELECT * FROM `docket` WHERE `REVIWER` = '" + UsernameProfile + "'";
            Statement PST = connection.createStatement();
            ResultSet resultSet = PST.executeQuery(SQL);
            while (resultSet.next()) {
                table.addRow(new Object[]{
                    resultSet.getString(1),
                    resultSet.getString(2),
                    resultSet.getString(3),
                    resultSet.getString(4),
                    resultSet.getString(5),
                    resultSet.getString(6),
                    resultSet.getString(7),
                    resultSet.getString(8),
                    resultSet.getString(9),
                    resultSet.getString(11),});
            }
            jTable1.setModel(table);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(REVIEWER.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REVIEWER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REVIEWER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REVIEWER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REVIEWER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new REVIEWER().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel HeaderPressed;
    private javax.swing.JPanel PanelLayer;
    private javax.swing.JPanel SC;
    private javax.swing.JPanel SideMenu;
    private javax.swing.JLabel UserLevel;
    private javax.swing.JLabel UserLevel1;
    private javax.swing.JPanel assign;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
